### PR TITLE
fix: handle buildUrl errors gracefully

### LINKED ISSUE #141: Panic in BuildUrl - error is not handled
We are seeing panics in our application.

While investigating, I figured out that `BuildUrl` function is ignoring error which is causing panic later in the flow.

This happens when you have wrong `ServiceSid` configured.

https://github.com/twilio/twilio-go/blob/main/client/request_handler.go#L32

### PR DESCRIPTION
**Pull request by kpritam**
fixes #141

### CODE REVIEW

File: client/request_handler_test.go [hunk 1]
```diff
@@ -15,35 +15,41 @@ func NewRequestHandler(accountSid string, authToken string) *client.RequestHandl
...
+	assert.Equal(t, "https://api.edge.region.twilio.com", assertAndGetURL(t, requestHandler, "https://api.twilio.com"))
+	assert.Equal(t, "https://api.edge.region.twilio.com", assertAndGetURL(t, requestHandler, "https://api.urlEdge.urlRegion.twilio.com"))
 }
 
 func TestRequestHandler_BuildHostRawHostWithoutPeriods(t *testing.T) {
 	requestHandler := NewRequestHandler("user", "pass")
-	assert.Equal(t, "https://prism_twilio:4010", requestHandler.BuildUrl("https://prism_twilio:4010"))
+	assert.Equal(t, "https://prism_twilio:4010", assertAndGetURL(t, requestHandler, "https://prism_twilio:4010"))
+}
+
```
Comment (JenniferMah) [inline client/request_handler_test.go:50]: Hi @kpritam! Thanks for your contribution! Could you add some tests to verify that errors are returned properly?

Comment (kpritam) [reply client/request_handler_test.go:52]: @JenniferMah have added test, please have a look.

**Review by childish-sambino — APPROVED** [review]
LGTM Thanks!
